### ISSUE TITLE
adauth.AuthenticateExtended call is not returning an expected ldap group

### ISSUE THREAD

**Issue by cmadarsh** [korylprince/go-ad-auth#15]
Hello,

I created a new ldap user in Windows Active Directory Users and Computers. When this new user is created by default it is a member of 'Domain Users' group. But when I used adauth.AuthenticateExtended call it did not return this group.

Then I created a new group say 'DCS' and made this new user member of 'DCS', then ideally the user is member of 'Domain Users' and 'DCS'. But the adauth.AuthenticateExtended call returned only 'DCS'. Note that I had passed both groups in the call.

After more investigation, in LDAP server I noticed that attribute 'member' of 'DCS' group had reference to the new user, but the 'member' attribute of 'Domain User' did not have reference to the user. 

In Windows Active Directory though it says user is member of both 'Domain User' and 'DCS', the AuthenticateExtended call returns only DCS, as attribute 'member' of 'Domain Users' does not mention this user.

So, 
does this library check the attributes before returning the group? or
By default, as user is not referred in 'Domain Users', is it LDAP configuration issue?

**Comment by korylprince** [comment]
By default, `Domain Users` is the primary group for users. This means a user's `primaryGroupID` attribute is set to the RID of the group. The group won't show up in the generated `memberOf` attribute of the user, and the user won't show up in the `member` attribute of the group.

Matching against the default group, while a valid use case, seems not to be useful to most. Unless you're doing something weird, every user that's able to authenticate will also be a part of that group. Checking if one of the groups passed to `AuthenticateExtended` is the primary group would add an extra LDAP query for every call. I'm not going to do that because most users would find it necessary.

Instead, in version v3.2.0, I've added [`*Conn.ObjectPrimaryGroup`](https://pkg.go.dev/github.com/korylprince/go-ad-auth/v3#Conn.ObjectPrimaryGroup), which you can use to manually check yourself:

```go
dn, err := conn.ObjectPrimaryGroup("cn", "John Smith")
if err != nil {
    // handle err
}

if dn != expectedGroup {
    // handle mismatch
}
```
