### ISSUE TITLE
Authentication on LDAP over TLS does not work

### ISSUE THREAD

**Issue by faurik** [korylprince/go-ad-auth#3]
Hello.

When I trying to authenticate via TLS on the server via TLS (port 636) - it throws an error:
```
panic: Connection error: LDAP Result Code 200 "Network Error": x509: cannot validate certificate for X.X.X.X because it doesn't contain any IP SANs.
```

My config:
```
config := &auth.Config{
	Server: "X.X.X.X",
	Port: 636,
	BaseDN: "ou=Users,dc=my,dc=example,dc=com",
	Security: auth.SecurityTLS,
}
```
The one way to avoid this error is change call of the function DialTLS on [line 27](https://github.com/korylprince/go-ad-auth/blob/master/conn.go#L27) from
```
conn, err := ldap.DialTLS("tcp", fmt.Sprintf("%s:%d", c.Server, c.Port), &tls.Config{ServerName: c.Server})
```
to
```
conn, err := ldap.DialTLS("tcp", fmt.Sprintf("%s:%d", c.Server, c.Port), &tls.Config{ServerName: c.Server, InsecureSkipVerify: true})
```
This method is not so good, because in InsecureScipVerify mode we are susceptible to man-in-the-middle attacks. 

Is there any way to fix it without using bad practices? Maybe I made mistake somewhere?

**Comment by korylprince** [comment]
This is an issue with your code, not this library. 
**TL;DR**: You need to use replace `Server: "X.X.X.X",` with `Server: "<server hostname>",`, most likely.

The error is telling you that your client can't verify the server's certificate because you've provided an IP and that IP is not in the certificate. That's how TLS verification works. It's going to verify the IP or hostname you've given it

It's the same reason you'll get an error in your browser when connecting to [https://216.58.194.100/](https://216.58.194.100/) instead of [https://www.google.com/](https://www.google.com/); The certificate for www.google.com doesn't list all the IPs it uses, it just lists www.google.com (and a few other domains.)

To fix this, you need to make sure your server has a certificate that's from a trusted CN. This could be one you purchased, a free one from LetsEncrypt, or possibly one you created (i.e. self-signed). In that last case, you'll need to make sure that the CN certificate you created is trusted on the client, or you'll get get another error.

Then in your client, connect with the hostname listed in the certificate (you'll need to make sure that hostname points to the correct server in your DNS.) The hostname will be checked to make sure it's in the cert, and the cert's CN will be checked to make sure it's trusted. If both of those things are correct, a secure, verified connection will be started.

If you can't provide those two things (a trusted CN and a certificate with the hostname in in it) then you'll have to use `InsecureSkipVerify: true` and be vulnerable to MitM attacks.

**Comment by faurik** [comment]
Thanks for the advice, replacing the IP with the hostname solved my problem.
